name: devexam
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Change language of app.
  easy_localization: ^3.0.0

  # For upload user data and user's exam history
  cloud_firestore: ^1.0.0 #^0.16.0

  # For authenticate
  firebase_auth: ^1.0.0 #^0.20.0+1

  # for manage firebase easily
  firebase_core: ^1.0.0 #^0.7.0

  # for upload profile picture
  firebase_storage: ^8.0.0 #^7.0.0

  # for make complex dart class
  equatable: ^1.2.5
  meta: ^1.2.4
  formz: ^0.3.2
  # intl: ^0.16.1

  # to save data localy
  shared_preferences: ^2.0.3

  # for manage complex state.
  flutter_bloc: ^6.1.1

  # For open photos of questions
  photo_view: ^0.10.3

  # for fetch image from internet without problem
  cached_network_image: #^2.5.0

  # for upload image as a profile picture - crop image
  image_picker: ^0.7.2 #^0.6.7+22
  image_cropper: ^1.3.1
  permission_handler: ^6.0.1 #^5.1.0+2

  # Develop complex UI in easy
  flutter_button: ^0.0.4
  flutter_spinkit:

  # Icons
  cupertino_icons: ^0.1.3
  material_design_icons_flutter: ^4.0.5755

  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  integration_test:
  #    sdk: flutter

flutter:
  uses-material-design: true

  assets:

  # Custom Images (icon, logo, image)
    - assets/custom/exam.png
    - assets/custom/test.png
    - assets/custom/good.png
    - assets/custom/better.png
    - assets/custom/bad.png
    - assets/custom/empty.png
    - assets/custom/logo.png
    - assets/custom/wifi.png

  # Images of jsons (Question images)
    - assets/img/none.png
    - assets/img/1/2.jpeg
    - assets/img/1/3.jpeg
    - assets/img/1/4.jpeg
    - assets/img/1/5.jpeg
    - assets/img/1/6.jpeg
    - assets/img/1/9.jpeg
    - assets/img/1/11.jpg
    - assets/img/1/13.jpg
    - assets/img/1/14.jpg
    - assets/img/1/16.jpg
    - assets/img/1/18.jpg
    - assets/img/1/19.jpg
    - assets/img/1/20.jpg
    - assets/img/1/40.jpeg
    - assets/img/1/41.jpg
    - assets/img/1/42.jpg
    - assets/img/1/43.jpg
    - assets/img/1/44.jpg
    - assets/img/1/44.jpg
    - assets/img/1/45.jpg
    - assets/img/1/46.jpg
    - assets/img/1/47.jpg
    - assets/img/1/48.jpg
    - assets/img/1/49.jpg
    - assets/img/1/50.jpg
    - assets/img/1/51.jpg
    - assets/img/1/52.jpg
    - assets/img/1/53.jpg
    - assets/img/1/54.jpg
    - assets/img/1/55.jpg
    - assets/img/1/56.jpg
    - assets/img/1/57.jpg
    - assets/img/1/58.jpg
    - assets/img/1/59.jpg
    - assets/img/1/60.jpg
    - assets/img/1/61.jpg
    - assets/img/1/62.jpg
    - assets/img/1/63.jpg
    - assets/img/1/64.jpg
    - assets/img/1/65.jpg
    - assets/img/1/66.jpg
    - assets/img/1/67.jpg
    - assets/img/1/68.jpg
    - assets/img/1/69.jpg
    - assets/img/1/70.jpg
    - assets/img/1/71.jpeg
    - assets/img/1/72.jpeg
    - assets/img/1/73.jpeg
    - assets/img/1/74.jpeg
    - assets/img/1/75.jpeg
    - assets/img/1/76.jpeg
    - assets/img/1/76.jpeg
    - assets/img/1/77.jpeg
    - assets/img/1/78.jpg
    - assets/img/1/79.jpeg
    - assets/img/1/80.jpeg
    - assets/img/1/81.jpeg
    - assets/img/1/82.jpeg
    - assets/img/1/83.jpeg
    - assets/img/1/84.jpeg
    - assets/img/1/85.jpeg
    - assets/img/1/86.jpeg
    - assets/img/1/87.jpeg
    - assets/img/1/88.jpeg
    - assets/img/1/89.jpeg
    - assets/img/1/90.jpeg
    - assets/img/1/91.jpg
    - assets/img/1/92.jpg
    - assets/img/1/93.jpg
    - assets/img/1/94.jpg
    - assets/img/1/95.jpg
    - assets/img/1/96.jpg
    - assets/img/1/97.jpg
    - assets/img/1/98.jpg
    - assets/img/1/99.jpg
    - assets/img/1/100.jpg
    - assets/img/1/101.jpg
    - assets/img/1/102.jpg
    - assets/img/1/103.jpg
    - assets/img/1/104.jpg
    - assets/img/1/105.jpg
    - assets/img/1/106.jpg
    - assets/img/1/107.jpg
    - assets/img/1/108.jpg
    - assets/img/1/109.jpg
    - assets/img/1/110.jpg
    - assets/img/1/111.jpg
    - assets/img/1/112.jpg
    - assets/img/1/113.jpg
    - assets/img/1/114.jpg
    - assets/img/1/116.jpg
    - assets/img/1/117.jpg
    - assets/img/1/118.jpg
    - assets/img/1/119.jpg
    - assets/img/1/120.jpg
    - assets/img/1/121.jpg
    - assets/img/1/122.jpg
    - assets/img/1/123.jpg
    - assets/img/1/124.jpg
    - assets/img/1/125.jpg
    - assets/img/1/126.jpg
    - assets/img/1/127.jpg
    - assets/img/1/128.jpg
    - assets/img/1/129.jpg
    - assets/img/1/130.jpg
    - assets/img/1/131.jpg
    - assets/img/1/132.jpg
    - assets/img/1/133.jpg
    - assets/img/1/134.jpg
    - assets/img/1/135.jpg
    - assets/img/1/136.jpg
    - assets/img/1/137.jpg
    - assets/img/1/138.jpg
    - assets/img/1/139.jpg
    - assets/img/1/140.jpg
    - assets/img/1/141.jpg
    - assets/img/1/142.jpg
    - assets/img/1/143.jpg
    - assets/img/1/145.jpg
    - assets/img/1/146.jpg
    - assets/img/1/148.jpg
    - assets/img/1/149.jpg
    - assets/img/1/150.jpg
    - assets/img/1/152.jpg
    - assets/img/1/153.jpg
    - assets/img/1/154.jpg
    - assets/img/1/155.jpg
    - assets/img/1/156.jpg
    - assets/img/1/157.jpg
    - assets/img/1/158.jpg
    - assets/img/1/160.jpg
    - assets/img/1/161.jpg
    - assets/img/1/162.jpg
    - assets/img/1/163.jpg
    - assets/img/1/164.jpg
    - assets/img/1/166.jpg
    - assets/img/1/169.jpg
    - assets/img/1/170.jpg
    - assets/img/1/171.jpg
    - assets/img/1/172.jpg
    - assets/img/1/173.jpg
    - assets/img/1/174.jpg
    - assets/img/1/175.jpg
    - assets/img/1/176.jpg
    - assets/img/1/177.jpg
    - assets/img/1/178.jpg
    - assets/img/1/179.jpg
    - assets/img/1/180.jpg
    - assets/img/1/182.jpg
    - assets/img/1/183.jpg
    - assets/img/1/184.jpg
    - assets/img/1/185.jpg
    - assets/img/1/186.jpg
    - assets/img/1/187.jpg
    - assets/img/1/188.jpg
    - assets/img/1/189.jpg
    - assets/img/1/190.jpg
    - assets/img/1/191.jpg
    - assets/img/1/192.jpg
    - assets/img/1/195.jpg
    - assets/img/1/196.jpg
    - assets/img/1/197.jpg
    - assets/img/1/198.jpg
    - assets/img/1/201.jpg
    - assets/img/1/203.jpg
    - assets/img/1/205.jpg
    - assets/img/1/207.jpg
    - assets/img/1/209.jpg
    - assets/img/1/210.jpg
    - assets/img/1/211.jpg
    - assets/img/1/212.jpg
    - assets/img/1/213.jpg
    - assets/img/1/214.jpg
    - assets/img/1/215.jpg
    - assets/img/1/216.jpg
    - assets/img/1/217.jpg
    - assets/img/1/218.jpg
    - assets/img/1/221.jpg
    - assets/img/1/222.jpg
    - assets/img/1/223.jpg
    - assets/img/1/225.jpg
    - assets/img/1/226.jpg
    - assets/img/1/228.jpg
    - assets/img/1/229.jpg
    - assets/img/1/230.jpg
    - assets/img/1/231.jpg
    - assets/img/1/232.jpg
    - assets/img/1/233.jpg
    - assets/img/1/234.jpg
    - assets/img/1/235.jpg
    - assets/img/1/236.jpg
    - assets/img/1/238.jpg
    - assets/img/1/239.jpg
    - assets/img/1/240.jpg
    - assets/img/1/241.jpg
    - assets/img/1/242.jpg
    - assets/img/1/243.jpg
    - assets/img/1/244.jpg
    - assets/img/1/245.jpg
    - assets/img/1/247.jpg
    - assets/img/1/248.jpg
    - assets/img/1/249.jpg
    - assets/img/1/250.jpg
    - assets/img/1/251.jpg
    - assets/img/1/252.jpg
    - assets/img/1/253.jpg
    - assets/img/1/254.jpg
    - assets/img/1/255.jpg
    - assets/img/1/256.jpg
    - assets/img/1/257.jpg
    - assets/img/1/258.jpg
    - assets/img/1/259.jpg
    - assets/img/1/260.jpg
    - assets/img/1/261.jpg
    - assets/img/1/262.jpg
    - assets/img/1/263.jpg
    - assets/img/1/264.jpg
    - assets/img/1/265.jpg
    - assets/img/1/266.jpg
    - assets/img/1/267.jpg
    - assets/img/1/268.jpg
    - assets/img/1/269.jpg
    - assets/img/1/270.jpg
    - assets/img/1/271.jpg
    - assets/img/1/272.jpg
    - assets/img/1/273.jpg
    - assets/img/1/274.jpg
    - assets/img/1/275.jpg
    - assets/img/1/276.jpg
    - assets/img/1/277.jpg
    - assets/img/1/278.jpg
    - assets/img/1/280.jpg
    - assets/img/1/281.jpg
    - assets/img/1/282.jpg
    - assets/img/1/284.jpg
    - assets/img/1/286.jpg
    - assets/img/1/287.jpg
    - assets/img/1/288.jpg
    - assets/img/1/289.jpg
    - assets/img/1/290.jpg
    - assets/img/1/291.jpg
    - assets/img/1/293.jpg
    - assets/img/1/295.jpg
    - assets/img/1/296.jpg
    - assets/img/1/297.jpg
    - assets/img/1/298.jpg
    - assets/img/1/299.jpg
    - assets/img/1/300.jpg
    - assets/img/1/301.jpg

    # Json Files 
    - assets/languages/az.json
    - assets/languages/ru.json
    - assets/json/az.json
    - assets/json/ru.json
